import Foundation

/// Localized strings for auth screens
/// Mirrors the web app's dictionary structure at t.pages.auth
enum AuthStrings {

    // MARK: - String Access

    /// Get a localized string for the given key and locale
    static func string(_ key: String, locale: LocalizationManager.AppLocale) -> String {
        let dictionary = locale == .norwegian ? norwegianStrings : englishStrings
        return dictionary[key] ?? key
    }

    // MARK: - Norwegian Strings

    private static let norwegianStrings: [String: String] = [
        // Login Screen
        "login.title": "Logg inn p\u{00E5} Tidex",
        "login.subtitle": "Velkommen tilbake! Logg inn for \u{00E5} fortsette",
        "login.emailOrPhoneLabel": "E-post eller telefonnummer",
        "login.emailOrPhonePlaceholder": "navn@eksempel.no eller +47 12345678",
        "login.passwordLabel": "Passord",
        "login.passwordOptionalLabel": "Passord (valgfritt)",
        "login.passwordPlaceholder": "Skriv inn passordet ditt",
        "login.phonePasswordHint": "La passordfeltet st\u{00E5} tomt for \u{00E5} motta en SMS-kode",
        "login.submitButton": "Logg inn",
        "login.emailOrPhoneReveal": "Logg inn med e-post eller telefon",
        "login.forgotPassword": "Glemt passord?",
        "login.noAccount": "Har du ikke en konto?",
        "login.createAccount": "Opprett konto",
        "login.separator": "eller",

        // Login Success Messages
        "login.success.smsSent": "En kode er sendt til telefonen din",

        // Login Errors
        "login.errors.fillEmailOrPhone": "Fyll inn e-post eller telefonnummer.",
        "login.errors.invalidEmailOrPhone": "Ugyldig e-post eller telefonnummer.",
        "login.errors.genericError": "En feil oppstod",
        "login.errors.googleSignInFailed": "Kunne ikke starte Google-innlogging. Pr\u{00F8}v igjen senere.",
        "login.errors.appleSignInFailed": "Kunne ikke starte Apple-innlogging. Pr\u{00F8}v igjen senere.",
        "login.errors.passwordRequired": "Passord er p\u{00E5}krevd",

        // OTP Screen
        "otp.title": "Skriv inn koden",
        "otp.subtitle": "Vi har sendt en kode til %@",
        "otp.submitButton": "Bekreft",
        "otp.resendCode": "Send kode p\u{00E5} nytt",
        "otp.backToLogin": "Tilbake til innlogging",

        // OAuth Buttons
        "oauth.continueWithGoogle": "Fortsett med Google",
        "oauth.continueWithApple": "Fortsett med Apple",
        "oauth.signInWithGoogle": "Logg inn med Google",
        "oauth.signInWithApple": "Logg inn med Apple",

        // MFA Screen
        "mfa.title": "To-faktor autentisering",
        "mfa.subtitle": "Skriv inn koden fra autentiseringsappen din",
        "mfa.codeLabel": "Bekreftelseskode",
        "mfa.codePlaceholder": "000000",
        "mfa.submitButton": "Bekreft",
        "mfa.backToLogin": "Tilbake til innlogging",
        "mfa.errors.codeRequired": "Vennligst skriv inn 6-sifret kode",
        "mfa.errors.challengeExpired": "Sesjonen har utl\u{00F8}pt. Pr\u{00F8}v igjen.",

        // Signup Screen
        "signup.title": "Opprett konto",
        "signup.subtitle": "Kom i gang med Tidex",
        "signup.emailOrPhoneLabel": "E-post eller telefonnummer",
        "signup.emailOrPhonePlaceholder": "navn@eksempel.no eller +47 12345678",
        "signup.emailLabel": "E-post",
        "signup.phoneLabel": "Telefonnummer",
        "signup.passwordLabel": "Passord",
        "signup.passwordPlaceholder": "Minst 8 tegn",
        "signup.passwordHint": "Passordet m\u{00E5} v\u{00E6}re minst 8 tegn",
        "signup.confirmPasswordLabel": "Bekreft passord",
        "signup.submitButton": "Opprett konto",
        "signup.hasAccount": "Har du allerede en konto?",
        "signup.login": "Logg inn",
        "signup.emailOrPhoneReveal": "Registrer med e-post eller telefon",
        "signup.backToSignup": "Tilbake",
        "signup.errors.emailOrPhoneRequired": "Fyll inn e-post eller telefonnummer",
        "signup.errors.invalidEmailOrPhone": "Ugyldig e-post eller telefonnummer",
        "signup.errors.passwordRequired": "Passord er p\u{00E5}krevd",
        "signup.errors.passwordTooShort": "Passordet m\u{00E5} v\u{00E6}re minst 8 tegn",
        "signup.errors.passwordMismatch": "Passordene samsvarer ikke",
        "signup.errors.termsRequired": "Du m\u{00E5} godta vilk\u{00E5}rene",
        "signup.success.emailSent": "En bekreftelseslenke er sendt til e-posten din",
        "signup.success.otpSent": "En kode er sendt til telefonen din",
        "signup.success.otpResent": "En ny kode er sendt",
        "signup.emailSent.title": "Sjekk e-posten din",
        "signup.emailSent.subtitle": "Vi har sendt en bekreftelseslenke",
        "signup.emailSent.instructions": "Klikk p\u{00E5} lenken i e-posten for \u{00E5} bekrefte kontoen din. Sjekk ogs\u{00E5} spam-mappen.",
        "signup.emailSent.backToLogin": "Tilbake til innlogging",
        "signup.terms.prefix": "Jeg godtar",
        "signup.terms.termsLink": "vilk\u{00E5}rene",
        "signup.terms.and": "og",
        "signup.terms.privacyLink": "personvern",

        // OTP Errors
        "otp.errors.codeRequired": "Vennligst skriv inn koden",
        "otp.errors.codeInvalid": "Koden m\u{00E5} v\u{00E6}re 6 siffer",

        // Reset Password Screen
        "resetPassword.title": "Tilbakestill passord",
        "resetPassword.subtitle": "Skriv inn e-post eller telefonnummer for \u{00E5} tilbakestille passordet",
        "resetPassword.emailOrPhoneLabel": "E-post eller telefonnummer",
        "resetPassword.emailOrPhonePlaceholder": "navn@eksempel.no eller +47 12345678",
        "resetPassword.emailLabel": "E-post",
        "resetPassword.hint": "Vi sender en kode eller lenke for \u{00E5} tilbakestille passordet",
        "resetPassword.submitButton": "Send tilbakestillingskode",
        "resetPassword.backToLogin": "Tilbake til innlogging",
        "resetPassword.newPassword.title": "Nytt passord",
        "resetPassword.newPassword.subtitle": "Skriv inn ditt nye passord",
        "resetPassword.newPasswordLabel": "Nytt passord",
        "resetPassword.newPasswordPlaceholder": "Minst 8 tegn",
        "resetPassword.confirmPasswordLabel": "Bekreft nytt passord",
        "resetPassword.confirmPasswordPlaceholder": "Skriv passordet p\u{00E5} nytt",
        "resetPassword.passwordHint": "Passordet m\u{00E5} v\u{00E6}re minst 8 tegn",
        "resetPassword.updatePasswordButton": "Oppdater passord",
        "resetPassword.success.title": "Ferdig!",
        "resetPassword.success.subtitle": "Passordet ditt er tilbakestilt",
        "resetPassword.success.emailSent": "En tilbakestillingslenke er sendt til e-posten din",
        "resetPassword.success.otpSent": "En kode er sendt til telefonen din",
        "resetPassword.success.otpResent": "En ny kode er sendt",
        "resetPassword.success.passwordUpdated": "Passordet er oppdatert",
        "resetPassword.success.emailInstructions": "Sjekk e-posten din for en tilbakestillingslenke. Sjekk ogs\u{00E5} spam-mappen.",
        "resetPassword.success.passwordUpdatedInstructions": "Passordet ditt er oppdatert. Du kan n\u{00E5} logge inn med det nye passordet.",
        "resetPassword.errors.emailOrPhoneRequired": "Fyll inn e-post eller telefonnummer",
        "resetPassword.errors.invalidEmailOrPhone": "Ugyldig e-post eller telefonnummer",
        "resetPassword.errors.passwordRequired": "Passord er p\u{00E5}krevd",
        "resetPassword.errors.passwordTooShort": "Passordet m\u{00E5} v\u{00E6}re minst 8 tegn",
        "resetPassword.errors.confirmPasswordRequired": "Bekreft passordet",
        "resetPassword.errors.passwordMismatch": "Passordene samsvarer ikke",

        // Legal
        "legal.termsOfService": "Vilk\u{00E5}r for bruk",
        "legal.privacyPolicy": "Personvernerkl\u{00E6}ring",
        "legal.termsOfServiceContent": "Vilk\u{00E5}r for bruk av Tidex...\n\nVed \u{00E5} bruke Tidex godtar du disse vilk\u{00E5}rene.",
        "legal.privacyPolicyContent": "Personvernerkl\u{00E6}ring for Tidex...\n\nVi tar personvernet ditt p\u{00E5} alvor.",

        // Accept Terms Screen
        "acceptTerms.title": "Vilk\u{00E5}r og personvern",
        "acceptTerms.description": "Du m\u{00E5} godta vilk\u{00E5}rene for \u{00E5} bruke Tidex",
        "acceptTerms.explanation": "For \u{00E5} fortsette m\u{00E5} du lese og godta v\u{00E5}re vilk\u{00E5}r for bruk og personvernerkl\u{00E6}ring.",
        "acceptTerms.viewTerms": "Vilk\u{00E5}r for bruk",
        "acceptTerms.viewPrivacy": "Personvernerkl\u{00E6}ring",
        "acceptTerms.acceptButton": "Godta og fortsett",
        "acceptTerms.declineButton": "Avsl\u{00E5} og logg ut",
        "acceptTerms.updated.title": "Oppdaterte vilk\u{00E5}r",
        "acceptTerms.updated.description": "Vilk\u{00E5}rene v\u{00E5}re har blitt oppdatert siden du sist godtok dem",
        "acceptTerms.updated.explanation": "Vi har oppdatert v\u{00E5}re vilk\u{00E5}r for bruk og personvernerkl\u{00E6}ring. Vennligst les gjennom endringene og godta de nye vilk\u{00E5}rene for \u{00E5} fortsette \u{00E5} bruke Tidex.",
        "acceptTerms.errors.updateFailed": "Kunne ikke lagre godkjenning. Pr\u{00F8}v igjen.",
        "acceptTerms.errors.genericError": "En feil oppstod. Pr\u{00F8}v igjen.",

        // Locale Switcher
        "locale.norwegian": "Norsk",
        "locale.english": "English",

        // Common
        "common.loading": "Laster...",
        "common.error": "Feil",
        "common.retry": "Pr\u{00F8}v igjen",
        "common.cancel": "Avbryt",
        "common.continue": "Fortsett",
        "common.back": "Tilbake",
        "common.done": "Ferdig",
        "common.save": "Lagre",
        "common.saveChanges": "Lagre endringer",

        // Tabs
        "tabs.home": "Hjem",
        "tabs.shifts": "Vakter",
        "tabs.add": "Legg til",
        "tabs.stats": "Statistikk",
        "tabs.sharing": "Venner",

        // Dashboard
        "dashboard.title": "Hjem",
        "dashboard.welcome": "Velkommen til Tidex!",
        "dashboard.subtitle": "Du er n\u{00E5} logget inn",
        "dashboard.signOut": "Logg ut",
        "dashboard.comingSoon": "Full dashboard kommer snart",
        "dashboard.comingSoonDescription": "Vi jobber med \u{00E5} bygge en fullstendig native iOS-app. F\u{00F8}lg med!",
        "dashboard.earnedToDate": "hittil",
        "dashboard.nextShift": "Neste vakt",
        "dashboard.today": "I dag",
        "dashboard.earnings": "Inntekt",
        "dashboard.noShifts": "Ingen vakter funnet",
        "dashboard.letsAddShift": "La oss legge til en vakt!",
        "dashboard.addShiftButton": "Legg til vakt",
        "dashboard.loadError": "Kunne ikke laste data",
        "dashboard.nextPayout": "Neste utbetaling",
        "dashboard.previousPayout": "Forrige utbetaling",
        "dashboard.payroll": "Utbetaling",
        "dashboard.gross": "Brutto",
        "dashboard.tax": "Skatt",
        "dashboard.shift": "vakt",
        "dashboard.shifts": "vakter",
        "dashboard.planned": "planlagt",
        "dashboard.hoursShort": "t",
        "dashboard.beforeTax": "før skatt",
        "dashboard.shiftPlanned": "vakt planlagt",
        "dashboard.shiftsPlanned": "vakter planlagt",
        "dashboard.backToToday": "Tilbake til i dag",
        "dashboard.swipeHint": "Sveip for \u{00E5} bytte m\u{00E5}ned",
        "dashboard.bestShift": "Beste vakt",
        "dashboard.noShiftsMonth": "Ingen vakter denne m\u{00E5}neden",
        "dashboard.noNextShift": "Ingen kommende vakter",

        // Placeholders
        "placeholder.shiftsDescription": "Vaktene dine vises her",
        "placeholder.addShift": "Legg til vakt",
        "placeholder.addShiftDescription": "Legg til en ny vakt her",
        "placeholder.statsDescription": "Statistikken din vises her",
        "placeholder.sharingDescription": "Del vakter med venner her",

        // User Menu
        "userMenu.settings": "Innstillinger",
        "userMenu.logout": "Logg ut",
        "userMenu.loggingOut": "Logger ut...",

        // Pull to Refresh
        "pullToRefresh.pullDown": "Dra ned for å oppdatere",
        "pullToRefresh.release": "Slipp for å oppdatere",
        "pullToRefresh.refreshing": "Oppdaterer...",

        // Onboarding
        "onboarding.skip": "Hopp over",
        "onboarding.welcome.title": "Vit nøyaktig hva du tjener",
        "onboarding.welcome.subtitle": "Registrer vakter. Se lønna. Ingen overraskelser.",

        "onboarding.paycheck.title": "Denne måneden tjente du...",
        "onboarding.paycheck.sample_label": "Eksempelberegning med prøvedata",
        "onboarding.paycheck.industry.retail": "Butikk",
        "onboarding.paycheck.industry.restaurant": "Restaurant",
        "onboarding.paycheck.industry.healthcare": "Helse",
        "onboarding.paycheck.base_pay": "Grunnlønn",
        "onboarding.paycheck.evening": "Kveldstillegg",
        "onboarding.paycheck.weekend": "Helgetillegg",
        "onboarding.paycheck.tax": "Skatt trukket",
        "onboarding.paycheck.net": "Netto utbetalt",

        "onboarding.slider.label": "Din timelønn",

        "onboarding.how.title": "Tre steg til klarhet",
        "onboarding.how.step1.title": "Logg vakten din",
        "onboarding.how.step1.desc": "Legg til start- og sluttid, ferdig",
        "onboarding.how.step2.title": "Se inntekten din",
        "onboarding.how.step2.desc": "Lønn beregnes automatisk",
        "onboarding.how.step3.title": "Følg med på måneden",
        "onboarding.how.step3.desc": "Dashbordet viser fremgangen din",
        "onboarding.how.outcome": "Alt beregnes automatisk",

        "onboarding.getstarted.title": "Klar til å ta kontroll?",
        "onboarding.getstarted.subtitle": "Opprett kontoen din på sekunder",
        "onboarding.getstarted.signup": "Opprett konto",
        "onboarding.getstarted.login": "Har du allerede en konto? Logg inn",

        "onboarding.personalize.title": "La oss gjøre dette ditt",
        "onboarding.personalize.subtitle": "Bare to raske ting, så er du inne",
        "onboarding.personalize.wage.label": "Timelønn",
        "onboarding.personalize.wage.helper": "Grunnlønn per time",
        "onboarding.personalize.wage.error": "Vennligst oppgi en gyldig timelønn",
        "onboarding.personalize.payday.label": "Lønningsdag",
        "onboarding.personalize.payday.helper": "Når får du utbetalt lønn?",
        "onboarding.personalize.payday.lastDay": "Siste",

        "onboarding.success.title": "Du er klar!",
        "onboarding.success.subtitle": "Legg til din første vakt for å se ekte inntekt",
        "onboarding.success.reassurance": "Du kan justere lønn, tillegg og skatt når som helst.",
        "onboarding.success.button": "Gå til dashbord",
        "onboarding.success.saving": "Lagrer innstillingene dine...",
        "onboarding.success.savingTitle": "Ett øyeblikk",
        "onboarding.success.errorTitle": "Noe gikk galt",
        "onboarding.success.errorSubtitle": "Vi kunne ikke lagre innstillingene dine",

        // Wage Screen
        "onboarding.wage.title": "Velg din lønnstype",
        "onboarding.wage.subtitle": "Vi trenger dette for å beregne lønna di",
        "onboarding.wage.tariff": "Tariff",
        "onboarding.wage.custom": "Timelønn",

        // Currency Selector
        "onboarding.currency.label": "Valuta",
        "onboarding.currency.title": "Velg valuta",

        // Supplements Screen
        "onboarding.supplements.title": "Tillegg",
        "onboarding.supplements.subtitle": "Legg til tillegg for kvelder, helger osv.",
        "onboarding.supplements.addRule": "Legg til tillegg",
        "onboarding.supplements.editRule": "Rediger tillegg",
        "onboarding.supplements.skip": "Hopp over",
        "onboarding.supplements.hint": "Tillegg brukes til å beregne ekstra lønn for arbeid på ubekvemme tider",
        "onboarding.supplements.save": "Lagre",
        "onboarding.supplements.daysLabel": "Hvilke dager?",
        "onboarding.supplements.timeLabel": "Tidspunkt",
        "onboarding.supplements.from": "Fra",
        "onboarding.supplements.to": "Til",
        "onboarding.supplements.typeLabel": "Type tillegg",
        "onboarding.supplements.fixedRate": "Fast beløp",
        "onboarding.supplements.percentRate": "Prosent",
        "onboarding.supplements.valueLabel": "Verdi",
        "onboarding.supplements.weekdays": "Man-Fre",
        "onboarding.supplements.weekend": "Helg",
        "onboarding.supplements.allDays": "Alle",
        "onboarding.supplements.weekdaysLong": "Man-Fre",
        "onboarding.supplements.weekendLong": "Lør-Søn",
        "onboarding.supplements.allDaysLong": "Alle dager",
        "onboarding.supplements.perHour": "kr/t",

        // Settings Accordion Screen
        "onboarding.settings.title": "Siste steg",
        "onboarding.settings.subtitle": "Tilpass innstillingene dine",
        "onboarding.settings.break.title": "Pausetrekk",
        "onboarding.settings.break.enable": "Aktiver automatisk pausetrekk",
        "onboarding.settings.break.hint": "Trekker pause automatisk for lange vakter",
        "onboarding.settings.break.default": "Standard: 30 min pause for vakter over 5,5 timer",
        "onboarding.settings.break.enabledSummary": "Aktivert • 30 min for 5,5t+ vakter",
        "onboarding.settings.break.disabledSummary": "Deaktivert",
        "onboarding.settings.tax.title": "Skattetrekk",
        "onboarding.settings.tax.enable": "Vis lønn etter skatt",
        "onboarding.settings.tax.hint": "Trekker skatt fra beregnet lønn",
        "onboarding.settings.tax.percentage": "Skatteprosent",
        "onboarding.settings.tax.disabledSummary": "Deaktivert",
        "onboarding.settings.payday.title": "Lønningsdag",
        "onboarding.settings.payday.hint": "Hvilken dag i måneden får du utbetalt lønn?",
        "onboarding.settings.payday.other": "Annen",
        "onboarding.settings.payday.customValue": "Lønningsdag: {day}. i måneden",

        // Add Shift
        "addShift.singleTitle": "Legg til vakter",
        "addShift.singleSubtitle": "Velg datoer først",
        "addShift.recurringTitle": "Faste vakter",
        "addShift.recurringSubtitle": "Velg ankerdatoer først",
        "addShift.modeSingle": "Enkel",
        "addShift.modeRecurring": "Fast",
        "addShift.startTime": "Starttid",
        "addShift.endTime": "Sluttid",
        "addShift.selectDates": "Velg datoer",
        "addShift.addShift": "Legg til vakt",
        "addShift.addShifts": "Legg til {count} vakter",
        "addShift.dateSelected": "dato valgt",
        "addShift.datesSelected": "{count} datoer valgt",
        "addShift.conflictSingular": "1 konflikt",
        "addShift.conflictPlural": "{n} konflikter",
        "addShift.rangeHint": "Trykk p\u{00E5} en annen dato for \u{00E5} fullf\u{00F8}re utvalget",
        "addShift.repeat": "Gjenta",
        "addShift.everyWeek": "hver uke",
        "addShift.everyNWeeks": "hver {n}. uke",
        "addShift.duration": "Varighet",
        "addShift.duration.indefinite": "Uendelig",
        "addShift.duration.months": "M\u{00E5}neder",
        "addShift.duration.years": "\u{00C5}r",
        "addShift.duration.endDate": "Sluttdato",
        "addShift.indefiniteHint": "Dette m\u{00F8}nsteret gjentas p\u{00E5} ubestemt tid",
        "addShift.monthSingular": "1 m\u{00E5}ned",
        "addShift.monthPlural": "{n} m\u{00E5}neder",
        "addShift.yearSingular": "1 \u{00E5}r",
        "addShift.yearPlural": "{n} \u{00E5}r",
        "addShift.selectAnchorDates": "Velg ankerdatoer",
        "addShift.previewShifts": "Forh\u{00E5}ndsvis vakter",

        // MFA Screen
        "onboarding.mfa.title": "Ekstra sikkerhet",
        "onboarding.mfa.subtitle": "Beskytt kontoen din med to-faktor autentisering",
        "onboarding.mfa.setup": "Sett opp 2FA",
        "onboarding.mfa.skip": "Gjør dette senere",
        "onboarding.mfa.benefit1.title": "Ekstra lag med sikkerhet",
        "onboarding.mfa.benefit1.desc": "Selv om noen får tak i passordet ditt, trenger de også telefonen din",
        "onboarding.mfa.benefit2.title": "Enkel verifisering",
        "onboarding.mfa.benefit2.desc": "Bruk en autentiseringsapp for raske engangskoder",
        "onboarding.mfa.benefit3.title": "Beskytt dine data",
        "onboarding.mfa.benefit3.desc": "Hold lønnsinformasjonen din trygg",
        "onboarding.mfa.enrolling": "Setter opp...",
        "onboarding.mfa.startSetup": "Start oppsett",
        "onboarding.mfa.setupTitle": "Sett opp 2FA",
        "onboarding.mfa.scanQR": "Skann QR-koden med autentiseringsappen din",
        "onboarding.mfa.manualEntry": "Eller skriv inn manuelt:",
        "onboarding.mfa.enterCode": "Skriv inn koden fra appen",
        "onboarding.mfa.verify": "Bekreft",
        "onboarding.mfa.addToPasswords": "Legg til i Passord",

        // Paywall
        "paywall.title": "Velg abonnement",
        "paywall.monthly": "Månedlig",
        "paywall.yearly": "Årlig",
        "paywall.savePercent": "Spar %d%%",
        "paywall.subscribe": "Abonner",
        "paywall.restorePurchases": "Gjenopprett kjøp",
        "paywall.currentPlan": "Din nåværende plan",
        "paywall.loading": "Laster planer...",
        "paywall.loadingButton": "Laster...",
        "paywall.perMonth": "per måned",
        "paywall.perYear": "per år",
        "paywall.termsOfUse": "Vilkår for bruk",
        "paywall.privacyPolicy": "Personvernerklæring",

        // Paywall - Tiers
        "paywall.tier.free": "Gratis",
        "paywall.tier.pro": "Pro",
        "paywall.tier.max": "Max",

        // Paywall - Pro Features
        "paywall.pro.feature1": "Ubegrenset antall måneder",
        "paywall.pro.feature2": "Avansert statistikk",
        "paywall.pro.feature3": "Eksporter til PDF/CSV",
        "paywall.pro.feature4": "Prioritert support",

        // Paywall - Max Features
        "paywall.max.feature1": "Alt i Pro",
        "paywall.max.feature2": "Wagey AI-assistent",
        "paywall.max.feature3": "Gjentakende vakter",
        "paywall.max.feature4": "Vaktdeling",
        "paywall.max.feature5": "Premium-temaer",

        // Paywall - Free Features
        "paywall.free.feature1": "Én måned med vakter",
        "paywall.free.feature2": "Grunnleggende statistikk",

        // Paywall - Shift Limit Context
        "paywall.shiftLimit.title": "Oppgrader for flere måneder",
        "paywall.shiftLimit.message": "Gratis-planen tillater vakter i én måned om gangen. Oppgrader for å spore vakter over flere måneder.",

        // Paywall - Generic Upgrade Context
        "paywall.upgrade.title": "Lås opp premium-funksjoner",
        "paywall.upgrade.message": "Få ubegrensede måneder, avansert statistikk, Wagey AI og mer.",

        // Month Limit Sheet (Free tier - add shifts to new month)
        "monthLimit.upgradeHeadline": "Lås opp flere måneder",
        "monthLimit.upgradeSubheadline": "Spor vakter på tvers av flere måneder",
        "monthLimit.feature1": "Ubegrenset antall måneder med vakter",
        "monthLimit.feature2": "Avansert lønnsstatistikk",
        "monthLimit.feature3": "Eksporter til PDF og CSV",
        "monthLimit.viewPlansButton": "Se abonnementer",
        "monthLimit.or": "eller",
        "monthLimit.deleteShiftsLink": "Slett vakter i andre måneder",
        "monthLimit.deleteTitle": "Slett vakter",
        "monthLimit.deleteExplanation": "For å legge til vakter i {targetMonth}, må vaktene i {otherMonths} slettes.",
        "monthLimit.deleteButton": "Slett vakter i andre måneder",
        "monthLimit.confirmDeleteMessage": "Er du sikker på at du vil slette alle vakter i {months}? Dette kan ikke angres.",
        "monthLimit.cancelDelete": "Avbryt",
        "monthLimit.confirmDeleteButton": "Slett {count} måned",
        "monthLimit.confirmDeleteButtonPlural": "Slett {count} måneder",
        "monthLimit.couldNotDeleteShifts": "Kunne ikke slette vakter. Prøv igjen.",
        "monthLimit.unexpectedError": "En uventet feil oppstod.",

        // Verification Required
        "verification.title": "Bekreft abonnement",
        "verification.offline.title": "Ingen internettforbindelse",
        "verification.offline.message": "Koble til internett for å bekrefte abonnementet ditt.",
        "verification.online.title": "Bekreft abonnementet ditt",
        "verification.online.message": "Vi kunne ikke bekrefte abonnementet ditt. Prøv igjen eller gjenopprett kjøpene dine.",
        "verification.retry": "Prøv igjen",

        // Shifts
        "shifts.weekLabel": "Uke",
        "shifts.noShiftsTitle": "Ingen vakter",
        "shifts.noShiftsCurrentMonth": "Legg til din første vakt for å se den her",
        "shifts.noShiftsOtherMonth": "Ingen vakter registrert denne måneden",
        "shifts.addShiftButton": "Legg til vakt",
        "shifts.loadError": "Kunne ikke laste vakter",
        "shifts.detailsTitle": "Vaktdetaljer",
        "shifts.timeSection": "Tid",
        "shifts.timeRange": "Tidsrom",
        "shifts.duration": "Varighet",
        "shifts.earningsSection": "Inntekt",
        "shifts.grossPay": "Bruttolønn",
        "shifts.taxDeduction": "Skattetrekk",
        "shifts.netPay": "Nettolønn",
        "shifts.recurringShift": "Gjentakende vakt",
        "shifts.recurringShiftDescription": "Denne vakten er generert fra et gjentakende mønster",
        "shifts.deleteButton": "Slett vakt",
        "shifts.deleteConfirmTitle": "Slett vakt?",
        "shifts.deleteConfirmMessage": "Er du sikker på at du vil slette denne vakten? Dette kan ikke angres.",
        "shifts.excludeButton": "Ekskluder denne datoen",
        "shifts.excludeConfirmTitle": "Ekskluder denne vakten?",
        "shifts.excludeConfirmMessage": "Denne datoen blir ekskludert fra den faste vakten. Vakten vil ikke lenger vises.",
        "shifts.excludedFromTotal": "Ikke inkludert i total",
        "shifts.basePay": "Grunnlønn",
        "shifts.supplementsSection": "Tillegg",
        "shifts.totalSupplement": "Totalt tillegg",
        "shifts.supplementLabel": "Tillegg",
        "shifts.customized": "Tilpasset",
        "shifts.details": "Detaljer",
        "shifts.move": "Flytt",
        "shifts.copy": "Kopier",
        "shifts.confirm": "Bekreft",
        "shifts.selectCopyTarget": "Trykk på en dato for å kopiere",
        "shifts.selectMoveTarget": "Trykk på en dato for å flytte",
        "shifts.copying": "Kopierer...",
        "shifts.moving": "Flytter...",
        "shifts.editTitle": "Rediger vakt",
        "shifts.editTimeSection": "Rediger tid",
        "shifts.editButton": "Rediger",
        "shifts.date": "Dato",
        "shifts.startTime": "Starttid",
        "shifts.endTime": "Sluttid",
        "shifts.crossMidnightInfo": "Vakten går over midnatt til neste dag",
        "shifts.virtualConversionInfo": "Endringer oppretter en ny vakt og ekskluderer denne datoen fra den faste vakten",

        // Sharing
        "sharing.title": "Deling",
        "sharing.earningsVisible": "Inntekt synlig",
        "sharing.earningsHidden": "Inntekt skjult",
        "sharing.noSharers": "Ingen deler med deg",
        "sharing.noSharersDescription": "N\u{00E5}r noen deler vaktene sine med deg, vil de vises her",
        "sharing.peopleWhoShareWithYou": "Folk som deler med deg",
        "sharing.loading": "Laster...",
        "sharing.loadingShifts": "Laster vakter...",
        "sharing.shifts": "vakter",
        "sharing.hours": "timer",
        "sharing.earnings": "Inntekt",
        "sharing.noShiftsThisMonth": "Ingen vakter denne m\u{00E5}neden",
        "sharing.noShiftsDescription": "Denne personen har ingen vakter registrert for denne m\u{00E5}neden",
        "sharing.lastUpdated": "Sist oppdatert",
        "sharing.hidden": "Skjult",
        "sharing.loadError": "Kunne ikke laste data",
        "sharing.back": "Tilbake",
        "sharing.statusActive": "Pågår nå",
        "sharing.synced": "synkronisert",

        // Sharing Tab
        "sharing.friendsTitle": "Venner",

        // Sharing Management Modal
        "sharing.manageTitle": "Administrer",
        "sharing.manageDescription": "Del vaktene dine med venner og kolleger slik at de kan f\u{00F8}lge med p\u{00E5} n\u{00E5}r du jobber.",
        "sharing.mutual": "Begge deler",
        "sharing.iShareWith": "Jeg deler med",
        "sharing.sharesWithMe": "Deler med meg",
        "sharing.noFriends": "Ingen venner enda",
        "sharing.noFriendsDescription": "Legg til venner for å dele vaktene dine",
        "sharing.addFriend": "Legg til venn",
        "sharing.emailOrPhone": "E-post eller telefonnummer",
        "sharing.showEarnings": "Vis inntjening",
        "sharing.shareBack": "Del tilbake",
        "sharing.remove": "Fjern",
        "sharing.add": "Legg til",
        "sharing.loadingFriends": "Laster venner...",
        "sharing.stopSharingWith": "Slutte å dele med %@?",
        "sharing.removeFromList": "Fjerne %@ fra listen?",

        // Sharing error messages
        "sharing.error.loadFriends": "Kunne ikke laste venner",
        "sharing.error.addFriend": "Kunne ikke legge til venn",
        "sharing.error.addFriendEmpty": "Vennligst oppgi en e-post eller telefonnummer",
        "sharing.error.updateSettings": "Kunne ikke oppdatere innstillinger",
        "sharing.error.updateNotifications": "Kunne ikke oppdatere varslingsinnstillinger",
        "sharing.error.removeShare": "Kunne ikke fjerne deling",
        "sharing.error.removePerson": "Kunne ikke fjerne personen",
        "sharing.error.shareBack": "Kunne ikke dele tilbake"
    ]

    // MARK: - English Strings

    private static let englishStrings: [String: String] = [
        // Login Screen
        "login.title": "Log in to Tidex",
        "login.subtitle": "Welcome back! Log in to continue",
        "login.emailOrPhoneLabel": "Email or phone number",
        "login.emailOrPhonePlaceholder": "name@example.com or +47 12345678",
        "login.passwordLabel": "Password",
        "login.passwordOptionalLabel": "Password (optional)",
        "login.passwordPlaceholder": "Enter your password",
        "login.phonePasswordHint": "Leave password empty to receive an SMS code",
        "login.submitButton": "Log in",
        "login.emailOrPhoneReveal": "Log in with email or phone",
        "login.forgotPassword": "Forgot password?",
        "login.noAccount": "Don't have an account?",
        "login.createAccount": "Create account",
        "login.separator": "or",

        // Login Success Messages
        "login.success.smsSent": "A code has been sent to your phone",

        // Login Errors
        "login.errors.fillEmailOrPhone": "Please enter email or phone number.",
        "login.errors.invalidEmailOrPhone": "Invalid email or phone number.",
        "login.errors.genericError": "An error occurred",
        "login.errors.googleSignInFailed": "Could not start Google sign-in. Please try again later.",
        "login.errors.appleSignInFailed": "Could not start Apple sign-in. Please try again later.",
        "login.errors.passwordRequired": "Password is required",

        // OTP Screen
        "otp.title": "Enter the code",
        "otp.subtitle": "We've sent a code to %@",
        "otp.submitButton": "Confirm",
        "otp.resendCode": "Resend code",
        "otp.backToLogin": "Back to login",

        // OAuth Buttons
        "oauth.continueWithGoogle": "Continue with Google",
        "oauth.continueWithApple": "Continue with Apple",
        "oauth.signInWithGoogle": "Sign in with Google",
        "oauth.signInWithApple": "Sign in with Apple",

        // MFA Screen
        "mfa.title": "Two-factor authentication",
        "mfa.subtitle": "Enter the code from your authenticator app",
        "mfa.codeLabel": "Verification code",
        "mfa.codePlaceholder": "000000",
        "mfa.submitButton": "Confirm",
        "mfa.backToLogin": "Back to login",
        "mfa.errors.codeRequired": "Please enter the 6-digit code",
        "mfa.errors.challengeExpired": "Session expired. Please try again.",

        // Signup Screen
        "signup.title": "Create account",
        "signup.subtitle": "Get started with Tidex",
        "signup.emailOrPhoneLabel": "Email or phone number",
        "signup.emailOrPhonePlaceholder": "name@example.com or +47 12345678",
        "signup.emailLabel": "Email",
        "signup.phoneLabel": "Phone number",
        "signup.passwordLabel": "Password",
        "signup.passwordPlaceholder": "At least 8 characters",
        "signup.passwordHint": "Password must be at least 8 characters",
        "signup.confirmPasswordLabel": "Confirm password",
        "signup.submitButton": "Create account",
        "signup.hasAccount": "Already have an account?",
        "signup.login": "Log in",
        "signup.emailOrPhoneReveal": "Sign up with email or phone",
        "signup.backToSignup": "Back",
        "signup.errors.emailOrPhoneRequired": "Please enter email or phone number",
        "signup.errors.invalidEmailOrPhone": "Invalid email or phone number",
        "signup.errors.passwordRequired": "Password is required",
        "signup.errors.passwordTooShort": "Password must be at least 8 characters",
        "signup.errors.passwordMismatch": "Passwords do not match",
        "signup.errors.termsRequired": "You must agree to the terms",
        "signup.success.emailSent": "A confirmation link has been sent to your email",
        "signup.success.otpSent": "A code has been sent to your phone",
        "signup.success.otpResent": "A new code has been sent",
        "signup.emailSent.title": "Check your email",
        "signup.emailSent.subtitle": "We've sent a confirmation link",
        "signup.emailSent.instructions": "Click the link in the email to confirm your account. Check your spam folder too.",
        "signup.emailSent.backToLogin": "Back to login",
        "signup.terms.prefix": "I agree to the",
        "signup.terms.termsLink": "terms of service",
        "signup.terms.and": "and",
        "signup.terms.privacyLink": "privacy policy",

        // OTP Errors
        "otp.errors.codeRequired": "Please enter the code",
        "otp.errors.codeInvalid": "Code must be 6 digits",

        // Reset Password Screen
        "resetPassword.title": "Reset password",
        "resetPassword.subtitle": "Enter your email or phone to reset your password",
        "resetPassword.emailOrPhoneLabel": "Email or phone number",
        "resetPassword.emailOrPhonePlaceholder": "name@example.com or +47 12345678",
        "resetPassword.emailLabel": "Email",
        "resetPassword.hint": "We'll send a code or link to reset your password",
        "resetPassword.submitButton": "Send reset code",
        "resetPassword.backToLogin": "Back to login",
        "resetPassword.newPassword.title": "New password",
        "resetPassword.newPassword.subtitle": "Enter your new password",
        "resetPassword.newPasswordLabel": "New password",
        "resetPassword.newPasswordPlaceholder": "At least 8 characters",
        "resetPassword.confirmPasswordLabel": "Confirm new password",
        "resetPassword.confirmPasswordPlaceholder": "Enter password again",
        "resetPassword.passwordHint": "Password must be at least 8 characters",
        "resetPassword.updatePasswordButton": "Update password",
        "resetPassword.success.title": "Done!",
        "resetPassword.success.subtitle": "Your password has been reset",
        "resetPassword.success.emailSent": "A reset link has been sent to your email",
        "resetPassword.success.otpSent": "A code has been sent to your phone",
        "resetPassword.success.otpResent": "A new code has been sent",
        "resetPassword.success.passwordUpdated": "Password has been updated",
        "resetPassword.success.emailInstructions": "Check your email for a reset link. Check your spam folder too.",
        "resetPassword.success.passwordUpdatedInstructions": "Your password has been updated. You can now log in with your new password.",
        "resetPassword.errors.emailOrPhoneRequired": "Please enter email or phone number",
        "resetPassword.errors.invalidEmailOrPhone": "Invalid email or phone number",
        "resetPassword.errors.passwordRequired": "Password is required",
        "resetPassword.errors.passwordTooShort": "Password must be at least 8 characters",
        "resetPassword.errors.confirmPasswordRequired": "Please confirm your password",
        "resetPassword.errors.passwordMismatch": "Passwords do not match",

        // Legal
        "legal.termsOfService": "Terms of Service",
        "legal.privacyPolicy": "Privacy Policy",
        "legal.termsOfServiceContent": "Terms of Service for Tidex...\n\nBy using Tidex you agree to these terms.",
        "legal.privacyPolicyContent": "Privacy Policy for Tidex...\n\nWe take your privacy seriously.",

        // Accept Terms Screen
        "acceptTerms.title": "Terms and Privacy",
        "acceptTerms.description": "You must accept the terms to use Tidex",
        "acceptTerms.explanation": "To continue, you must read and accept our Terms of Service and Privacy Policy.",
        "acceptTerms.viewTerms": "Terms of Service",
        "acceptTerms.viewPrivacy": "Privacy Policy",
        "acceptTerms.acceptButton": "Accept and Continue",
        "acceptTerms.declineButton": "Decline and Sign Out",
        "acceptTerms.updated.title": "Updated Terms",
        "acceptTerms.updated.description": "Our terms have been updated since you last accepted",
        "acceptTerms.updated.explanation": "We have updated our Terms of Service and Privacy Policy. Please review the changes and accept the new terms to continue using Tidex.",
        "acceptTerms.errors.updateFailed": "Could not save acceptance. Please try again.",
        "acceptTerms.errors.genericError": "An error occurred. Please try again.",

        // Locale Switcher
        "locale.norwegian": "Norsk",
        "locale.english": "English",

        // Common
        "common.loading": "Loading...",
        "common.error": "Error",
        "common.retry": "Try again",
        "common.cancel": "Cancel",
        "common.continue": "Continue",
        "common.back": "Back",
        "common.done": "Done",
        "common.save": "Save",
        "common.saveChanges": "Save changes",

        // Tabs
        "tabs.home": "Home",
        "tabs.shifts": "Shifts",
        "tabs.add": "Add",
        "tabs.stats": "Stats",
        "tabs.sharing": "Friends",

        // Dashboard
        "dashboard.title": "Home",
        "dashboard.welcome": "Welcome to Tidex!",
        "dashboard.subtitle": "You are now logged in",
        "dashboard.signOut": "Sign out",
        "dashboard.comingSoon": "Full dashboard coming soon",
        "dashboard.comingSoonDescription": "We're working on building a fully native iOS app. Stay tuned!",
        "dashboard.earnedToDate": "to date",
        "dashboard.nextShift": "Next shift",
        "dashboard.today": "Today",
        "dashboard.earnings": "Earnings",
        "dashboard.noShifts": "No shifts found",
        "dashboard.letsAddShift": "Let's add a shift!",
        "dashboard.addShiftButton": "Add Shift",
        "dashboard.loadError": "Failed to load data",
        "dashboard.nextPayout": "Next payout",
        "dashboard.previousPayout": "Previous payout",
        "dashboard.payroll": "Payroll",
        "dashboard.gross": "Gross",
        "dashboard.tax": "Tax",
        "dashboard.shift": "shift",
        "dashboard.shifts": "shifts",
        "dashboard.planned": "planned",
        "dashboard.hoursShort": "h",
        "dashboard.beforeTax": "before tax",
        "dashboard.shiftPlanned": "shift planned",
        "dashboard.shiftsPlanned": "shifts planned",
        "dashboard.backToToday": "Back to today",
        "dashboard.swipeHint": "Swipe to change month",
        "dashboard.bestShift": "Best shift",
        "dashboard.noShiftsMonth": "No shifts this month",
        "dashboard.noNextShift": "No upcoming shifts",

        // Placeholders
        "placeholder.shiftsDescription": "Your shifts will appear here",
        "placeholder.addShift": "Add Shift",
        "placeholder.addShiftDescription": "Add a new shift here",
        "placeholder.statsDescription": "Your statistics will appear here",
        "placeholder.sharingDescription": "Share shifts with friends here",

        // User Menu
        "userMenu.settings": "Settings",
        "userMenu.logout": "Log out",
        "userMenu.loggingOut": "Logging out...",

        // Pull to Refresh
        "pullToRefresh.pullDown": "Pull down to refresh",
        "pullToRefresh.release": "Release to refresh",
        "pullToRefresh.refreshing": "Refreshing...",

        // Onboarding
        "onboarding.skip": "Skip",
        "onboarding.welcome.title": "Know exactly what you earn",
        "onboarding.welcome.subtitle": "Track shifts. See your pay. No surprises.",

        "onboarding.paycheck.title": "This month, you earned...",
        "onboarding.paycheck.sample_label": "Example calculation using sample shifts",
        "onboarding.paycheck.industry.retail": "Retail",
        "onboarding.paycheck.industry.restaurant": "Restaurant",
        "onboarding.paycheck.industry.healthcare": "Healthcare",
        "onboarding.paycheck.base_pay": "Base pay",
        "onboarding.paycheck.evening": "Evening supplements",
        "onboarding.paycheck.weekend": "Weekend bonus",
        "onboarding.paycheck.tax": "Tax deducted",
        "onboarding.paycheck.net": "Net pay",

        "onboarding.slider.label": "Your hourly rate",

        "onboarding.how.title": "Three steps to clarity",
        "onboarding.how.step1.title": "Log your shift",
        "onboarding.how.step1.desc": "Add start time, end time, done",
        "onboarding.how.step2.title": "See your earnings",
        "onboarding.how.step2.desc": "Wages calculated automatically",
        "onboarding.how.step3.title": "Track your month",
        "onboarding.how.step3.desc": "Dashboard shows your progress",
        "onboarding.how.outcome": "All calculated automatically",

        "onboarding.getstarted.title": "Ready to take control?",
        "onboarding.getstarted.subtitle": "Create your account in seconds",
        "onboarding.getstarted.signup": "Create Account",
        "onboarding.getstarted.login": "Already have an account? Log in",

        "onboarding.personalize.title": "Let's make this yours",
        "onboarding.personalize.subtitle": "Just two quick things, then you're in",
        "onboarding.personalize.wage.label": "Hourly wage",
        "onboarding.personalize.wage.helper": "Your base hourly rate",
        "onboarding.personalize.wage.error": "Please enter a valid hourly wage",
        "onboarding.personalize.payday.label": "Payroll day",
        "onboarding.personalize.payday.helper": "When do you get paid?",
        "onboarding.personalize.payday.lastDay": "Last",

        "onboarding.success.title": "You're all set!",
        "onboarding.success.subtitle": "Add your first shift to see real earnings",
        "onboarding.success.reassurance": "You can adjust wages, supplements, and tax anytime.",
        "onboarding.success.button": "Go to Dashboard",
        "onboarding.success.saving": "Saving your settings...",
        "onboarding.success.savingTitle": "One moment",
        "onboarding.success.errorTitle": "Something went wrong",
        "onboarding.success.errorSubtitle": "We couldn't save your settings",

        // Wage Screen
        "onboarding.wage.title": "Choose your wage type",
        "onboarding.wage.subtitle": "We need this to calculate your earnings",
        "onboarding.wage.tariff": "Tariff",
        "onboarding.wage.custom": "Hourly rate",

        // Currency Selector
        "onboarding.currency.label": "Currency",
        "onboarding.currency.title": "Select currency",

        // Supplements Screen
        "onboarding.supplements.title": "Supplements",
        "onboarding.supplements.subtitle": "Add supplements for evenings, weekends, etc.",
        "onboarding.supplements.addRule": "Add supplement",
        "onboarding.supplements.editRule": "Edit supplement",
        "onboarding.supplements.skip": "Skip",
        "onboarding.supplements.hint": "Supplements are used to calculate extra pay for inconvenient hours",
        "onboarding.supplements.save": "Save",
        "onboarding.supplements.daysLabel": "Which days?",
        "onboarding.supplements.timeLabel": "Time",
        "onboarding.supplements.from": "From",
        "onboarding.supplements.to": "To",
        "onboarding.supplements.typeLabel": "Supplement type",
        "onboarding.supplements.fixedRate": "Fixed amount",
        "onboarding.supplements.percentRate": "Percent",
        "onboarding.supplements.valueLabel": "Value",
        "onboarding.supplements.weekdays": "Mon-Fri",
        "onboarding.supplements.weekend": "Weekend",
        "onboarding.supplements.allDays": "All",
        "onboarding.supplements.weekdaysLong": "Mon-Fri",
        "onboarding.supplements.weekendLong": "Sat-Sun",
        "onboarding.supplements.allDaysLong": "All days",
        "onboarding.supplements.perHour": "/h",

        // Settings Accordion Screen
        "onboarding.settings.title": "Final step",
        "onboarding.settings.subtitle": "Customize your settings",
        "onboarding.settings.break.title": "Break deduction",
        "onboarding.settings.break.enable": "Enable automatic break deduction",
        "onboarding.settings.break.hint": "Deducts break time for long shifts",
        "onboarding.settings.break.default": "Default: 30 min break for shifts over 5.5 hours",
        "onboarding.settings.break.enabledSummary": "Enabled • 30 min for 5.5h+ shifts",
        "onboarding.settings.break.disabledSummary": "Disabled",
        "onboarding.settings.tax.title": "Tax deduction",
        "onboarding.settings.tax.enable": "Show pay after tax",
        "onboarding.settings.tax.hint": "Deducts tax from calculated pay",
        "onboarding.settings.tax.percentage": "Tax rate",
        "onboarding.settings.tax.disabledSummary": "Disabled",
        "onboarding.settings.payday.title": "Payday",
        "onboarding.settings.payday.hint": "Which day of the month do you get paid?",
        "onboarding.settings.payday.other": "Other",
        "onboarding.settings.payday.customValue": "Payday: {day}th of the month",

        // Add Shift
        "addShift.singleTitle": "Add shifts",
        "addShift.singleSubtitle": "Select dates first",
        "addShift.recurringTitle": "Recurring shifts",
        "addShift.recurringSubtitle": "Select anchor dates first",
        "addShift.modeSingle": "Single",
        "addShift.modeRecurring": "Fixed",
        "addShift.startTime": "Start time",
        "addShift.endTime": "End time",
        "addShift.selectDates": "Select dates",
        "addShift.addShift": "Add shift",
        "addShift.addShifts": "Add {count} shifts",
        "addShift.dateSelected": "date selected",
        "addShift.datesSelected": "{count} dates selected",
        "addShift.conflictSingular": "1 conflict",
        "addShift.conflictPlural": "{n} conflicts",
        "addShift.rangeHint": "Tap another date to complete range",
        "addShift.repeat": "Repeat",
        "addShift.everyWeek": "every week",
        "addShift.everyNWeeks": "every {n} weeks",
        "addShift.duration": "Duration",
        "addShift.duration.indefinite": "Indefinite",
        "addShift.duration.months": "Months",
        "addShift.duration.years": "Years",
        "addShift.duration.endDate": "End date",
        "addShift.indefiniteHint": "This pattern will repeat indefinitely",
        "addShift.monthSingular": "1 month",
        "addShift.monthPlural": "{n} months",
        "addShift.yearSingular": "1 year",
        "addShift.yearPlural": "{n} years",
        "addShift.selectAnchorDates": "Select anchor dates",
        "addShift.previewShifts": "Preview shifts",

        // MFA Screen
        "onboarding.mfa.title": "Extra security",
        "onboarding.mfa.subtitle": "Protect your account with two-factor authentication",
        "onboarding.mfa.setup": "Set up 2FA",
        "onboarding.mfa.skip": "Do this later",
        "onboarding.mfa.benefit1.title": "Extra layer of security",
        "onboarding.mfa.benefit1.desc": "Even if someone gets your password, they still need your phone",
        "onboarding.mfa.benefit2.title": "Easy verification",
        "onboarding.mfa.benefit2.desc": "Use an authenticator app for quick one-time codes",
        "onboarding.mfa.benefit3.title": "Protect your data",
        "onboarding.mfa.benefit3.desc": "Keep your earnings information safe",
        "onboarding.mfa.enrolling": "Setting up...",
        "onboarding.mfa.startSetup": "Start setup",
        "onboarding.mfa.setupTitle": "Set up 2FA",
        "onboarding.mfa.scanQR": "Scan the QR code with your authenticator app",
        "onboarding.mfa.manualEntry": "Or enter manually:",
        "onboarding.mfa.enterCode": "Enter the code from your app",
        "onboarding.mfa.verify": "Verify",
        "onboarding.mfa.addToPasswords": "Add to Passwords",

        // Paywall
        "paywall.title": "Choose a Plan",
        "paywall.monthly": "Monthly",
        "paywall.yearly": "Yearly",
        "paywall.savePercent": "Save %d%%",
        "paywall.subscribe": "Subscribe",
        "paywall.restorePurchases": "Restore Purchases",
        "paywall.currentPlan": "Current Plan",
        "paywall.loading": "Loading plans...",
        "paywall.loadingButton": "Loading...",
        "paywall.perMonth": "per month",
        "paywall.perYear": "per year",
        "paywall.termsOfUse": "Terms of Use",
        "paywall.privacyPolicy": "Privacy Policy",

        // Paywall - Tiers
        "paywall.tier.free": "Free",
        "paywall.tier.pro": "Pro",
        "paywall.tier.max": "Max",

        // Paywall - Pro Features
        "paywall.pro.feature1": "Unlimited months",
        "paywall.pro.feature2": "Advanced statistics",
        "paywall.pro.feature3": "Export to PDF/CSV",
        "paywall.pro.feature4": "Priority support",

        // Paywall - Max Features
        "paywall.max.feature1": "Everything in Pro",
        "paywall.max.feature2": "Wagey AI Assistant",
        "paywall.max.feature3": "Recurring shifts",
        "paywall.max.feature4": "Shift sharing",
        "paywall.max.feature5": "Premium themes",

        // Paywall - Free Features
        "paywall.free.feature1": "One month of shifts",
        "paywall.free.feature2": "Basic statistics",

        // Paywall - Shift Limit Context
        "paywall.shiftLimit.title": "Upgrade to Add More Months",
        "paywall.shiftLimit.message": "Free plan allows shifts in one month at a time. Upgrade to track shifts across multiple months.",

        // Paywall - Generic Upgrade Context
        "paywall.upgrade.title": "Unlock Premium Features",
        "paywall.upgrade.message": "Get unlimited months, advanced statistics, Wagey AI, and more.",

        // Month Limit Sheet (Free tier - add shifts to new month)
        "monthLimit.upgradeHeadline": "Unlock More Months",
        "monthLimit.upgradeSubheadline": "Track shifts across multiple months",
        "monthLimit.feature1": "Unlimited months of shifts",
        "monthLimit.feature2": "Advanced wage statistics",
        "monthLimit.feature3": "Export to PDF and CSV",
        "monthLimit.viewPlansButton": "View Plans",
        "monthLimit.or": "or",
        "monthLimit.deleteShiftsLink": "Delete shifts in other months",
        "monthLimit.deleteTitle": "Delete Shifts",
        "monthLimit.deleteExplanation": "To add shifts in {targetMonth}, shifts in {otherMonths} must be deleted.",
        "monthLimit.deleteButton": "Delete shifts in other months",
        "monthLimit.confirmDeleteMessage": "Are you sure you want to delete all shifts in {months}? This cannot be undone.",
        "monthLimit.cancelDelete": "Cancel",
        "monthLimit.confirmDeleteButton": "Delete {count} month",
        "monthLimit.confirmDeleteButtonPlural": "Delete {count} months",
        "monthLimit.couldNotDeleteShifts": "Could not delete shifts. Please try again.",
        "monthLimit.unexpectedError": "An unexpected error occurred.",

        // Verification Required
        "verification.title": "Verify Subscription",
        "verification.offline.title": "No Internet Connection",
        "verification.offline.message": "Connect to the internet to verify your subscription status.",
        "verification.online.title": "Verify Your Subscription",
        "verification.online.message": "We couldn't verify your subscription. Please try again or restore your purchases.",
        "verification.retry": "Try Again",

        // Shifts
        "shifts.weekLabel": "Week",
        "shifts.noShiftsTitle": "No shifts",
        "shifts.noShiftsCurrentMonth": "Add your first shift to see it here",
        "shifts.noShiftsOtherMonth": "No shifts recorded this month",
        "shifts.addShiftButton": "Add Shift",
        "shifts.loadError": "Failed to load shifts",
        "shifts.detailsTitle": "Shift Details",
        "shifts.timeSection": "Time",
        "shifts.timeRange": "Time Range",
        "shifts.duration": "Duration",
        "shifts.earningsSection": "Earnings",
        "shifts.grossPay": "Gross Pay",
        "shifts.taxDeduction": "Tax Deduction",
        "shifts.netPay": "Net Pay",
        "shifts.recurringShift": "Recurring Shift",
        "shifts.recurringShiftDescription": "This shift is generated from a recurring pattern",
        "shifts.deleteButton": "Delete Shift",
        "shifts.deleteConfirmTitle": "Delete Shift?",
        "shifts.deleteConfirmMessage": "Are you sure you want to delete this shift? This cannot be undone.",
        "shifts.excludeButton": "Exclude This Date",
        "shifts.excludeConfirmTitle": "Exclude This Shift?",
        "shifts.excludeConfirmMessage": "This date will be excluded from the recurring pattern. The shift will no longer appear.",
        "shifts.excludedFromTotal": "Not included in total",
        "shifts.basePay": "Base Pay",
        "shifts.supplementsSection": "Supplements",
        "shifts.totalSupplement": "Total Supplement",
        "shifts.supplementLabel": "Supplement",
        "shifts.customized": "Customized",
        "shifts.details": "Details",
        "shifts.move": "Move",
        "shifts.copy": "Copy",
        "shifts.confirm": "Confirm",
        "shifts.selectCopyTarget": "Tap a date to copy to",
        "shifts.selectMoveTarget": "Tap a date to move to",
        "shifts.copying": "Copying...",
        "shifts.moving": "Moving...",
        "shifts.editTitle": "Edit Shift",
        "shifts.editTimeSection": "Edit Time",
        "shifts.editButton": "Edit",
        "shifts.date": "Date",
        "shifts.startTime": "Start time",
        "shifts.endTime": "End time",
        "shifts.crossMidnightInfo": "Shift continues past midnight to the next day",
        "shifts.virtualConversionInfo": "Changes will create a new shift and exclude this date from the recurring pattern",

        // Sharing
        "sharing.title": "Sharing",
        "sharing.earningsVisible": "Earnings visible",
        "sharing.earningsHidden": "Earnings hidden",
        "sharing.noSharers": "No one is sharing with you",
        "sharing.noSharersDescription": "When someone shares their shifts with you, they will appear here",
        "sharing.peopleWhoShareWithYou": "People who share with you",
        "sharing.loading": "Loading...",
        "sharing.loadingShifts": "Loading shifts...",
        "sharing.shifts": "shifts",
        "sharing.hours": "hours",
        "sharing.earnings": "Earnings",
        "sharing.noShiftsThisMonth": "No shifts this month",
        "sharing.noShiftsDescription": "This person has no shifts recorded for this month",
        "sharing.lastUpdated": "Last updated",
        "sharing.hidden": "Hidden",
        "sharing.loadError": "Failed to load data",
        "sharing.back": "Back",
        "sharing.statusActive": "Active now",
        "sharing.synced": "synced",

        // Sharing Tab
        "sharing.friendsTitle": "Friends",

        // Sharing Management Modal
        "sharing.manageTitle": "Manage",
        "sharing.manageDescription": "Share your shifts with friends and colleagues so they can see when you work.",
        "sharing.mutual": "Both share",
        "sharing.iShareWith": "I share with",
        "sharing.sharesWithMe": "Shares with me",
        "sharing.noFriends": "No friends yet",
        "sharing.noFriendsDescription": "Add friends to share your shifts",
        "sharing.addFriend": "Add friend",
        "sharing.emailOrPhone": "Email or phone number",
        "sharing.showEarnings": "Show earnings",
        "sharing.shareBack": "Share back",
        "sharing.remove": "Remove",
        "sharing.add": "Add",
        "sharing.loadingFriends": "Loading friends...",
        "sharing.stopSharingWith": "Stop sharing with %@?",
        "sharing.removeFromList": "Remove %@ from list?",

        // Sharing error messages
        "sharing.error.loadFriends": "Could not load friends",
        "sharing.error.addFriend": "Could not add friend",
        "sharing.error.addFriendEmpty": "Please enter an email or phone number",
        "sharing.error.updateSettings": "Could not update settings",
        "sharing.error.updateNotifications": "Could not update notification settings",
        "sharing.error.removeShare": "Could not remove share",
        "sharing.error.removePerson": "Could not remove person",
        "sharing.error.shareBack": "Could not share back"
    ]
}
