import Foundation

// Widget strings live in the app catalog as widget.* keys and use the generated symbols.

extension LocalizedStringResource {
  // MARK: - Motivational Salutes
  internal static let widgetSaluteKeys: [LocalizedStringResource] = [
    "salute.01",
    "salute.02",
    "salute.03",
    "salute.04",
    "salute.05",
    "salute.06",
    "salute.07",
    "salute.08",
    "salute.09",
    "salute.10",
    "salute.11",
    "salute.12",
    "salute.13",
    "salute.14",
    "salute.15",
    "salute.16",
    "salute.17",
    "salute.18",
    "salute.19",
    "salute.20",
    "salute.21",
    "salute.22",
    "salute.23",
    "salute.24",
    "salute.25",
    "salute.26",
    "salute.27",
    "salute.28",
    "salute.29",
    "salute.30",
    "salute.31",
    "salute.32",
    "salute.33",
    "salute.34",
    "salute.35",
    "salute.36",
    "salute.37",
    "salute.38",
    "salute.39",
    "salute.40",
    "salute.41",
    "salute.42",
    "salute.43",
    "salute.44",
    "salute.45",
    "salute.46",
    "salute.47",
    "salute.48",
    "salute.49",
    "salute.50",
  ]
}
